// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ouruljadnkfwcanzyxih.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im91cnVsamFkbmtmd2Nhbnp5eGloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxNDM1ODYsImV4cCI6MjA1NzcxOTU4Nn0.LIFy_O9wdJG6U7T2bC_YZRV_R-g_LutojUvrGPio4Ng";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);